[variables]
NODE_ENV = "production"
NEXT_TELEMETRY_DISABLED = "1"
HOSTNAME = "0.0.0.0"
PORT = "3000"

[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
cmds = ["npm ci --legacy-peer-deps --prefer-offline --no-audit"]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "node .next/standalone/server.js" 